MiniCourse.WebUI/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;

namespace MiniCourse.WebUI.Controllers
{
    public class UserController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MiniCourse.WebUI/ViewComponents/BasketCountViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MiniCourse.WebUI.Baskets;

namespace MiniCourse.WebUI.ViewComponents
{
    public class BasketCountViewComponent(IBasketService basketService): ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(string userId)
        {

            var basketRequest = await basketService.GetBasketByUserIdAsync();

            int basketCount = 0;

            if(basketRequest.AnyError)
                return View(basketCount);
            basketCount = basketRequest.Data.Items.Count();

            // Sayıyı View ile dön
            return View(basketCount);
        }
    }
}

MiniCourse.WebUI/ViewComponents/CatDropDownViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MiniCourse.WebUI.Categories;
using MiniCourse.WebUI.Courses;

namespace MiniCourse.WebUI.ViewComponents
{
    public class CatDropDownViewComponent(ICategoryService categoryService): ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var categories = await categoryService.GetCategoriesAsync();

            return View(categories.Data);
        }
    }
}

MiniCourse.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MiniCourse</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MiniCourse.WebUI.styles.css" asp-append-version="true" />
    <link href="~/sweetalert2/sweetalert2.min.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light shadow-sm">
        <div class="container-fluid px-4 px-lg-5">
            <a class="navbar-brand" href="/">MiniCourse</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                    <li class="nav-item dropdown ">
                        <a class="nav-link dropdown-toggle active" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Kategoriler</a>
                        @await Component.InvokeAsync("CatDropDown")
                    </li>
                    <li class="nav-item"><a class="nav-link active" aria-current="page" asp-controller="Courses" asp-action="Index">Kurslar</a></li>

                    <form class="d-flex" role="search">
                        <input autocomplete="off" id="headerSearch" class="form-control me-2 border-gray  header-search" type="search" placeholder="Kurs Ara" aria-label="Search">
                        <div class="spinner-border spinner-border-sm spinnerSearch d-none  " id="buttonSpinner" role="status" aria-hidden="true"></div>
                    </form>


                </ul>

                <div class="ms-auto d-flex">
                    <form class="d-flex">
                        <a asp-controller="Basket" asp-action="Index" class="btn btn-outline-dark">
                            <i class="bi-cart-fill me-1"></i>
                            <i class="bi bi-basket3-fill"></i>
                            <svg class="mx-1 mb-1" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-basket3-fill" viewBox="0 0 16 16">
                                <path d="M5.757 1.071a.5.5 0 0 1 .172.686L3.383 6h9.234L10.07 1.757a.5.5 0 1 1 .858-.514L13.783 6H15.5a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5H.5a.5.5 0 0 1-.5-.5v-1A.5.5 0 0 1 .5 6h1.717L5.07 1.243a.5.5 0 0 1 .686-.172zM2.468 15.426.943 9h14.114l-1.525 6.426a.75.75 0 0 1-.729.574H3.197a.75.75 0 0 1-.73-.574z" />
                            </svg>
                            Sepet
                            @await Component.InvokeAsync("BasketCount")
                        </a>
                    </form>
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                @{ string title = (User.Identity.IsAuthenticated ? User.Identity.Name : "Giriş Yap");}

                                @title
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                @if (!User.Identity.IsAuthenticated)
                                {
                                    <li><a class="dropdown-item" asp-controller="auth" asp-action="SignIn">Giriş Yap</a></li>
                                    <li><a class="dropdown-item" asp-controller="auth" asp-action="SignUp">Kayıt Ol</a></li>
                                }

                                @if (User.Identity.IsAuthenticated)
                                {
                                    <li><a class="dropdown-item" asp-controller="Member" asp-action="Profile">Profile Git</a></li>
                                    <li><a class="dropdown-item" asp-controller="Order" asp-action="Index">Siparişlerim</a></li>
                                    @if (User.IsInRole("SuperAdmin"))
                                    {
                                        <li><a class="dropdown-item" asp-area="Admin" asp-controller="Home" asp-action="Index">Yönetim Paneli</a></li>
                                        <li><a class="dropdown-item" asp-controller="Home" asp-action="SampleErrors">Örnek Hatalar</a></li>
                                    }
                                    <li><a class="dropdown-item" asp-controller="auth" asp-action="SignOut">Çıkış Yap</a></li>


                                }
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>
    <div id="courseSearchResult" class="">

    </div>
    @if (TempData["SuccessMessage"] != null)
    {
        <div class="server-alert-success">
            @TempData["SuccessMessage"]
        </div>
    }

    @if (TempData["ErrorMessage"] != null)
    {
        <div class="server-alert-danger">
            @TempData["ErrorMessage"]
        </div>
    }

    @if (TempData["InfoMessage"] != null)
    {
        <div class="server-alert-info">
            @TempData["InfoMessage"]
        </div>
    }


    <section class="py-5">
        @RenderBody()
    </section>

    <footer class="py-3 my-4">
        <ul class="nav justify-content-center border-bottom pb-3 mb-3">
            <li class="nav-item"><a asp-controller="Home" asp-action="Index" class="nav-link px-2 text-muted">Ana Sayfa</a></li>
            <li class="nav-item"><a asp-controller="Courses" asp-action="Index" class="nav-link px-2 text-muted">Kurslar</a></li>
            <li class="nav-item"><a href="https://localhost:7230/swagger/index.html" class="nav-link px-2 text-muted">API</a></li>
        </ul>
        <p class="text-center text-muted">© 2022 MiniCourse</p>
    </footer>

    <div id="customToast" class="toast align-items-center text-bg-primary border-0" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="d-flex">
            <div class="toast-body" id="toastMessage">
                Hello, world! This is a toast message.
            </div>
            <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
    </div>




    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/microsoft-signalr/signalr.min.js"></script>
    <script src="~/sweetalert2/sweetalert2.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/search.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MiniCourse.WebUI/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Yönetim Paneli</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @@media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>

    <link href="~/css/sidebars.css" rel="stylesheet" />

</head>
<body>
    <main>
        <div class="b-example-divider"></div>

        <div class="flex-shrink-0 p-3 bg-white" style="width: 280px">
            <h4 class="fw-semibold">Yönetim Paneli</h4>
            <div class="border-top my-3"></div>
            <ul class="list-unstyled ps-0">
                <li class="mb-1">
                    <button class="btn btn-toggle align-items-center rounded collapsed"
                            data-bs-toggle="collapse"
                            data-bs-target="#home-collapse"
                            aria-expanded="true">
                        Kullanıcılar
                    </button>
                    <div class="collapse" id="home-collapse">
                        <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                            <li><a asp-controller="User" asp-action="Index" class="link-dark rounded">Kullanıcı Listesi</a></li>
                            <li><a asp-controller="User" asp-action="Index" class="link-dark rounded">Kullanıcı Ekle</a></li>

                        </ul>
                    </div>
                </li>

                <li class="border-top my-3"></li>
                <li class="mb-1">
                    <button class="btn btn-toggle align-items-center rounded collapsed"
                            data-bs-toggle="collapse"
                            data-bs-target="#account-collapse"
                            aria-expanded="false">
                        Account
                    </button>
                    <div class="collapse" id="account-collapse">
                        <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                            <li><a href="#" class="link-dark rounded">New...</a></li>
                            <li><a href="#" class="link-dark rounded">Profile</a></li>
                            <li><a href="#" class="link-dark rounded">Settings</a></li>
                            <li><a href="#" class="link-dark rounded">Sign out</a></li>
                        </ul>
                    </div>
                </li>
            </ul>
        </div>
        <div class="b-example-divider"></div>

        <section class="p-5">
            @RenderBody()
        </section>
    </main>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/sidebars.js"></script>
</body>
</html>