MiniCourse.WebUI/Controllers/PaymentController.cs
using Azure;
using Microsoft.AspNetCore.Mvc;
using MiniCourse.WebUI.Orders;
using MiniCourse.WebUI.Payments;
using MiniCourse.WebUI.Payments.ViewModels;

namespace MiniCourse.WebUI.Controllers
{
    public class PaymentController(IOrderService orderService,IPaymentService paymentService) : Controller
    {
        public async Task<IActionResult> PaymentPage()
        {
            var result = await orderService.CreateOrderAsync();

            if (result.AnyError)
                return RedirectToAction(nameof(Index), "Basket");

            //burda payment sayfasına baska model de gidebilir
            ViewBag.OrderId = result.Data.OrderId;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> PaymentPage(PaymentViewModel model)
        {
            var response = await paymentService.ProcessPaymentAsync(model);

            if (response.AnyError)
            {
                foreach (var error in response.Errors!)
                {
                    ModelState.AddModelError(string.Empty, error);
                }

                return View(model);
            }

            return RedirectToAction("Success", "Order");
        }
    }
}

MiniCourse.WebUI/ViewComponents/PaymentSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MiniCourse.WebUI.Baskets;
using MiniCourse.WebUI.Baskets.DTOs;
using MiniCourse.WebUI.Baskets.ViewModels;

namespace MiniCourse.WebUI.ViewComponents
{
    public class PaymentSummaryViewComponent(IBasketService basketService):ViewComponent
   
    {
        public async Task<IViewComponentResult> InvokeAsync(string userId)
        {

            var basketRequest = await basketService.GetBasketDetailAsync();

            var basketSummeryModal = new BasketDetailViewModel();

            if (basketRequest.AnyError)
                return View(basketSummeryModal);

            basketSummeryModal = basketRequest.Data;

            return View(basketSummeryModal);
        }
    }
}

MiniCourse.WebUI/Views/Payment/PaymentPage.cshtml
@{
    ViewData["Title"] = "PaymentPage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model PaymentViewModel

<div class="container">
    <div class="row g-5">
        <div class="col-md-5 col-lg-4 order-md-last">


            @await Component.InvokeAsync("PaymentSummary")



        </div>
        <div class="col-md-7 col-lg-8">
            <h4 class="mb-3">Fatura Bilgileri</h4>
            <div asp-validation-summary="ModelOnly" class="alert alert-danger" role="alert"></div>
            <form id="paymentForm" asp-controller="Payment" asp-action="PaymentPage" method="post" class="needs-validation" novalidate>
                <input type="hidden" asp-for="OrderId"  value="@ViewBag.OrderId" />
                <div class="row g-3">
                    <div class="col-sm-6">
                        <label asp-for="NameForBill" class="form-label">İsim</label>
                        <input asp-for="NameForBill" class="form-control" value="">
                        <span asp-validation-for="NameForBill" class="text-danger"></span>
                    </div>

                    <div class="col-sm-6">
                        <label asp-for="LastNameForBill" class="form-label">Soy İsim</label>
                        <input asp-for="LastNameForBill" class="form-control" value="">
                        <span asp-validation-for="LastNameForBill" class="text-danger"></span>
                    </div>

                    <div class="col-12">
                        <label asp-for="AdressForBill" class="form-label">Address</label>
                        <input asp-for="AdressForBill" class="form-control">
                        <span asp-validation-for="AdressForBill" class="text-danger"></span>
                    </div>


                </div>

                <hr class="my-4">

                <h4 class="mb-3">Ödeme Bilgileri</h4>
                <div class="row gy-3">
                    <div class="col-md-6">
                        <label asp-for="CardHolderName" class="form-label">Kart sahibinin ismi</label>
                        <input asp-for="CardHolderName" class="form-control">
                        <span asp-validation-for="CardHolderName" class="text-danger"></span>

                    </div>

                    <div class="col-md-6">
                        <label asp-for="CardNumber" class="form-label">Kredi karti numarasi</label>
                        <input asp-for="CardNumber" class="form-control">
                        <span asp-validation-for="CardNumber" class="text-danger"></span>
                    </div>

                    <div class="col-md-3">
                        <label asp-for="ExpiryDate" class="form-label">Son Kullanma Tarihi</label>
                        <input asp-for="ExpiryDate" class="form-control">
                        <span asp-validation-for="ExpiryDate" class="text-danger"></span>
                    </div>

                    <div class="col-md-3">
                        <label asp-for="CVV" class="form-label">CVV</label>
                        <input asp-for="CVV" class="form-control">
                        <span asp-validation-for="CVV" class="text-danger"></span>
                    </div>
                </div>

                <hr class="my-4">

                <button id="paymentButton" class="w-100 btn btn-outline-dark btn-lg" type="submit">
                    <div class="spinner-border spinner-border-sm d-none" id="buttonSpinnerPayment" role="status" aria-hidden="true"></div>
                    <span id="buttonText">Ödeme Yap</span>

                </button>
            </form>
        </div>
    </div>
</div>

@if (!ViewData.ModelState.IsValid)
{
    @section Scripts{
        <script>
            $(document).ready(function () {

            });
            $("#paymentButton").prop("disabled", false);
            $("#buttonSpinnerPayment").css("display", "none");
        </script>
    }
}

@section Scripts
{
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

    <script>
        $(document).ready(function () {
            $("#paymentForm").on("submit", function (e) {
                var $form = $(this);
                var $button = $("#paymentButton");
                var $spinner = $("#buttonSpinnerPayment");
                var $buttonText = $("#buttonText");

                if (!$form.valid()) {
                    e.preventDefault();
                    return;
                }

                $spinner.removeClass("d-none");
                $buttonText.text("Ödeme İşleniyor...");
                $button.prop("disabled", true);
            });
        });
    </script>
}